<?php
/**
 * @file
 * Handles user creation in the provider with information from WAYF login.
 */

/**
 * Implements hook_permission().
 */
function ding_wayf_dk_create_user_permission() {
  return array(
    'administer wayf user creation' => array(
      'title' => t('Administer WAYF (user creation)'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ding_wayf_dk_create_user_menu() {
  $items = array();

  $items['wayf/info/create-user-page'] = array(
    'title' => 'Create new user information page',
    'description' => 'Create new user using WAYF login.',
    'page callback' => 'ding_wayf_dk_create_user_info_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['wayf/info/create-user-notice'] = array(
    'title' => 'User creation notice',
    'description' => 'Notice about account creation.',
    'page callback' => 'ding_wayf_dk_create_user_notice',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_wayf_dk_create_user_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_form_wayf_dk_login__settings_form_alter();
 */
function ding_wayf_dk_create_user_form_wayf_dk_login__settings_form_alter(&$form, &$form_state, $form_id) {
  $form['user'] = array(
    '#type' => 'fieldset',
    '#title' => t('Create user'),
    '#group' => 'tabs',
  );

  // Define before create info page
  $form['user']['ding_wayf_user_create_before_info'] = array(
    '#type' => 'fieldset',
    '#tree' => TRUE,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('User creating info pager (before)'),
    '#description' => t('Information to display on the page displayed when the user clicks on the create user link.'),
  );

  $defaults = variable_get('ding_wayf_user_create_before_info', array());
  $form['user']['ding_wayf_user_create_before_info']['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => isset($defaults['title']) ? $defaults['title'] : '',
  );

  $form['user']['ding_wayf_user_create_before_info']['content'] = array(
    '#type' => 'textarea',
    '#title' => t('Content'),
    '#default_value' => isset($defaults['content']) ? $defaults['content'] : '',
  );

  $form['user']['ding_wayf_user_create_before_info']['link'] = array(
    '#type' => 'textfield',
    '#title' => t('Link title'),
    '#default_value' => isset($defaults['link']) ? $defaults['link'] : '',
  );

  // Accepting text.
  $form['user']['ding_wayf_user_create_accpect_text'] = array(
    '#type' => 'textarea',
    '#title' => t('Accept text'),
    '#default_value' => variable_get('ding_wayf_user_create_accpect_text', ''),
    '#description' => t('The text that is display next to the user create accept check box.'),
  );

  // Define after create info page
  $form['user']['ding_wayf_user_create_after_info'] = array(
    '#type' => 'fieldset',
    '#tree' => TRUE,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#title' => t('User creating info pager (after)'),
    '#description' => t('Information to display on the page displayed when the user have sent a creation request.'),
  );

  $defaults = variable_get('ding_wayf_user_create_after_info', array());
  $form['user']['ding_wayf_user_create_after_info']['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => isset($defaults['title']) ? $defaults['title'] : '',
  );

  $form['user']['ding_wayf_user_create_after_info']['content'] = array(
    '#type' => 'textarea',
    '#title' => t('Content'),
    '#default_value' => isset($defaults['content']) ? $defaults['content'] : '',
  );
}

/**
 * Implements hook_theme().
 */
function ding_wayf_dk_create_user_theme($existing, $type, $theme, $path) {
  return array(
    'ding_wayf_dk_info_page' => array(
      'template' => 'ding-wayf-dk-info-page',
      'variables' => array(
        'title' => array(),
        'content' => array(),
        'link' => NULL,
      ),
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Menu callback for information page before user creation.
 */
function ding_wayf_dk_create_user_info_page() {
  // Get texts from the configuration.
  $values = variable_get('ding_wayf_user_create_before_info', array());

  return array(
    '#theme' => 'ding_wayf_dk_info_page',
    '#title' => empty($values['title']) ? t('Not configured.') : $values['title'],
    '#content' => empty($values['content']) ? t('Please configure WAYF configuration to get content on this page under <a href="/admin/config/people/wayf">admin/config/people/wayf</a>.') : $values['content'],
    '#link' => array(
      '#theme' => 'link',
      '#text' => empty($values['link']) ? t('Register as new user') : $values['link'],
      '#path' => 'wayf/consume',
      '#options' => array(
        'attributes' => array(
          'class' => array(),
        ),
        'query' => array(
          'destination' => 'wayf/info/create-user-form'
        ),
        'html' => TRUE,
      ),
    ),
  );
}

/**
 * Menu callback for information page after user creation.
 */
function ding_wayf_dk_create_user_notice() {
  // Get texts from the configuration.
  $values = variable_get('ding_wayf_user_create_after_info', array());

  return array(
    '#theme' => 'ding_wayf_dk_info_page',
    '#title' => empty($values['title']) ? t('Not configured.') : $values['title'],
    '#content' => empty($values['content']) ? t('Please configure WAYF configuration to get content on this page under <a href="/admin/config/people/wayf">admin/config/people/wayf</a>.') : $values['content'],
  );
}
